backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Páginas"
    editor:
      preview: false
    files:
      - file: "src/pages/index.md"
        label: "Página Inicial"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - label: Banner do Topo
            name: topBanner
            widget: object
            fields: 
              - {label: Título, name: title, widget: string}
              - {label: Subtítulo, name: subtitle, widget: string}
              - {label: Imagem de Fundo, name: bgImage, widget: image}
              - {label: "Camada no Fundo", name: "overlay", widget: "boolean"}
              - label: Botão de ação
                name: button
                widget: object
                fields:
                  - {label: Texto, name: buttonText, widget: string}
                  - {label: Link, name: buttonLink, widget: string}
            
          - label: Seção Serviços
            name: servicesSection
            widget: object
            fields: 
              - {label: Título, name: title, widget: string}
              - {label: Descrição, name: description, widget: string}
              - label: "Serviços" 
                name: "services" 
                widget: "list" 
                fields: 
                  - {label: "Título", name: "title", widget: "string"} 
                  - {label: "Descrição", name: "description", widget: "text"}
                  - label: "Ícone" 
                    name: "icon" 
                    widget: "object"
                    fields:
                      - {label: Imagem, name: image, widget: image}
                      - {label: "Legenda do Ícone", name: "imageAlt", widget: "string"}

          - label: Seção Coleção Pati
            name: collectionPatiSection
            widget: object
            fields: 
              - {label: Título, name: title, widget: string}
              - {label: Descrição, name: description, widget: text}
              - label: "Imagem em destaque" 
                name: "mainImage" 
                widget: "object"
                fields:
                  - {label: Imagem, name: image, widget: image}
                  - {label: "Legenda da Imagem", name: "imageAlt", widget: "string"}
              - {label: "Camada no Fundo", name: "overlay", widget: "boolean"}
              - {label: Imagem de Fundo, name: bgImage, widget: image}

          - label: "SEO"
            name: seo
            widget: "object"
            fields:
              - {label: "Título", name: title, widget: string}
              - {label: "Descrição", name: description, widget: string}

          - label: "OpenGraph"
            name: opengraph
            widget: "object"
            fields:
              - {label: "Título", name: title, widget: string}
              - {label: "Descrição", name: description, widget: string}
              - label: "Imagem"
                name: image
                widget: "object"
                fields:
                  - {label: "Imagem", name: imageUrl, widget: image}
                  - {label: "Descrição da Imagem", name: imageAlt, widget: string}
          
      - file: "src/pages/about/index.md"
        label: "Sobre"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: Imagem do cabeçalho, name: image, widget: image}
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Subtítulo", name: "subtitle", widget: "string"}
          - {label: "Conteúdo", name: "body", widget: "markdown"}
          - label: "SEO"
            name: seo
            widget: "object"
            fields:
              - {label: "Título", name: title, widget: string}
              - {label: "Descrição", name: description, widget: string}

          - label: "OpenGraph"
            name: opengraph
            widget: "object"
            fields:
              - {label: "Título", name: title, widget: string}
              - {label: "Descrição", name: description, widget: string}
              - label: "Imagem"
                name: image
                widget: "object"
                fields:
                  - {label: "Imagem", name: imageUrl, widget: image}
                  - {label: "Descrição da Imagem", name: imageAlt, widget: string}

      - file: "src/pages/projetos/index.md"
        label: "Projetos"
        name: "projects"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "projetos-page"}
          - {label: Imagem do cabeçalho, name: image, widget: image}
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Subtítulo", name: "subtitle", widget: "string"}
          - {label: "Conteúdo", name: "body", widget: "markdown"}
          - label: "SEO"
            name: seo
            widget: "object"
            fields:
              - {label: "Título", name: title, widget: string}
              - {label: "Descrição", name: description, widget: string}

          - label: "OpenGraph"
            name: opengraph
            widget: "object"
            fields:
              - {label: "Título", name: title, widget: string}
              - {label: "Descrição", name: description, widget: string}
              - label: "Imagem"
                name: image
                widget: "object"
                fields:
                  - {label: "Imagem", name: imageUrl, widget: image}
                  - {label: "Descrição da Imagem", name: imageAlt, widget: string}

      - file: "src/pages/propostas/index.md"
        label: "Propostas"
        name: "proposes"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "propostas-page"}
          - {label: Imagem do cabeçalho, name: image, widget: image}
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Subtítulo", name: "subtitle", widget: "string"}
          - {label: "Conteúdo", name: "body", widget: "markdown"}
          - label: "SEO"
            name: seo
            widget: "object"
            fields:
              - {label: "Título", name: title, widget: string}
              - {label: "Descrição", name: description, widget: string}

          - label: "OpenGraph"
            name: opengraph
            widget: "object"
            fields:
              - {label: "Título", name: title, widget: string}
              - {label: "Descrição", name: description, widget: string}
              - label: "Imagem"
                name: image
                widget: "object"
                fields:
                  - {label: "Imagem", name: imageUrl, widget: image}
                  - {label: "Descrição da Imagem", name: imageAlt, widget: string}
          
      - file: "src/pages/trajetoria/index.md"
        label: "Trajetória"
        name: "timeline"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "trajetoria-page"}
          - {label: Imagem do cabeçalho, name: image, widget: image}
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Subtítulo", name: "subtitle", widget: "string"}
          - label: "Eventos" 
            name: "eventos" 
            widget: "list" 
            fields: 
              - {label: "Título", name: "title", widget: "string"} 
              - {label: "Local", name: "local", widget: "string"}
              - {label: "Descrição", name: "description", widget: "text"}
              - {label: "Data/Período", name: "date", widget: "string"}
              - {label: Imagem do Evento, name: image, widget: image}
              - {label: "Legenda da Imagem", name: "imageAlt", widget: "string"}
          
          - label: "SEO"
            name: seo
            widget: "object"
            fields:
              - {label: "Título", name: title, widget: string}
              - {label: "Descrição", name: description, widget: string}

          - label: "OpenGraph"
            name: opengraph
            widget: "object"
            fields:
              - {label: "Título", name: title, widget: string}
              - {label: "Descrição", name: description, widget: string}
              - label: "Imagem"
                name: image
                widget: "object"
                fields:
                  - {label: "Imagem", name: imageUrl, widget: image}
                  - {label: "Descrição da Imagem", name: imageAlt, widget: string}

      - file: "src/pages/fotos/index.md"
        label: "Galeria de Fotos"
        name: "gallery"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "fotos-page"}
          - {label: Imagem do cabeçalho, name: image, widget: image}
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Subtítulo", name: "subtitle", widget: "string"}
          - label: "Imagens" 
            name: "fotos" 
            widget: "list" 
            fields: 
              - {label: "Título", name: "title", widget: "string"} 
              - {label: "Imagem", name: "image", widget: "image"}
          
          - label: "SEO"
            name: seo
            widget: "object"
            fields:
              - {label: "Título", name: title, widget: string}
              - {label: "Descrição", name: description, widget: string}

          - label: "OpenGraph"
            name: opengraph
            widget: "object"
            fields:
              - {label: "Título", name: title, widget: string}
              - {label: "Descrição", name: description, widget: string}
              - label: "Imagem"
                name: image
                widget: "object"
                fields:
                  - {label: "Imagem", name: imageUrl, widget: image}
                  - {label: "Descrição da Imagem", name: imageAlt, widget: string}

      - file: "src/pages/config/index.md"
        label: "Configurações"
        name: "config"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "config-page"}
          - label: "Instagram" 
            name: "instagram" 
            widget: "object"
            fields:
              - {label: "Link Completo", name: "fullLink", widget: "string"}
              - {label: "Username", name: "shortLink", widget: "string"}
          - label: "Facebook" 
            name: "facebook" 
            widget: "object"
            fields:
              - {label: "Link Completo", name: "fullLink", widget: "string"}
              - {label: "Username", name: "shortLink", widget: "string"}
          - {label: "E-mail", name: "email", widget: "string"}
          - {label: "Telefone", name: "phone", widget: "string"}
          - {label: "Ícone da Navbar", name: "icon", widget: "image"}
      
      # - file: "src/pages/products/index.md"
      #   label: "Products Page"
      #   name: "products"
      #   fields:
      #     - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
      #     - {label: Title, name: title, widget: string}
      #     - {label: Image, name: image, widget: image}
      #     - {label: Heading, name: heading, widget: string}
      #     - {label: Description, name: description, widget: string}
      #     - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
      #     - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      #     - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
      #     - {label: Full_image, name: full_image, widget: image}
      #     - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}

  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  #Collection Categories
  - label: "Categorias"
    name: "categories"
    folder: "_content/categories"
    create: true
    identifier_field: name
    editor:
      preview: false
    fields:
      - {label: "Nome", name: name, widget: string}
      - {label: "Descrição", name: description, widget: string, required: false}
      - {label: "Ativo", name: active, widget: boolean, default: true}
